PANDARIA: add ack operator
cnrancher/system-charts pull request #111
Opened 2021-07-16 01:07 UTC by NewGr8Player

2021-07-16 05:38 UTC, Jason-ZW requested changes
缺少question.yml?

2021-07-16 05:38 UTC, Jason-ZW commented on charts/rancher-ack-operator/v1.0.100/templates/_helpers.tpl
> +
没有release name trunc 方法？

2021-07-16 05:38 UTC, Jason-ZW commented on charts/rancher-ack-operator/v1.0.100/Chart.yaml
> +  catalog.cattle.io/auto-install: rancher-ack-operator-crd=match
这块为什么跟开源的gke和eks有区别？

2021-07-16 05:39 UTC, jianghang8421 requested changes
另外，如果chart对rancher版本有限制，需要增加questions.yaml,通过`rancher_min_version`，`rancher_max_version`来控制

2021-07-16 05:39 UTC, jianghang8421 commented on charts/rancher-ack-operator/v1.0.100/Chart.yaml
> +appVersion: v1.0.100
这个appversion的来源是什么？chart 里用的ack-operator镜像是0.0.1版本的，appversion应该与应用的版本对应。

2021-07-16 06:26 UTC, NewGr8Player commented on charts/rancher-ack-operator/v1.0.100/templates/_helpers.tpl
> +
这里的名字应是固定的，可以不加release name truncate
https://github.com/rancher/rancher/blob/1b81a0615ddef614e41c8ca53ccb309c447ac350/pkg/controllers/dashboard/hostedcluster/controller.go#L17-L42

2021-07-19 03:59 UTC, Jason-ZW commented on charts/rancher-ack-operator/v1.0.100/values.yaml
> +burst: ""
只是确认下？这些都没有默认值？

2021-07-19 04:02 UTC, NewGr8Player commented on charts/rancher-ack-operator/v1.0.100/values.yaml
> +burst: ""
chart 这边目前没有默认值，在operator中缺省的时候有默认值

2021-07-19 04:16 UTC, Jason-ZW approved these changes
LGTM

2021-07-21 03:39 UTC, jianghang8421 approved these changes
LGTM

2021-08-24 01:11 UTC, merged