[2.5] PANDARIA: Add F5CIS 0.0.2 chart with appversion 2.5.1
cnrancher/system-charts pull request #118
Opened 2021-08-26 07:13 UTC by jianghang8421

https://github.com/cnrancher/pandaria/issues/1664

2021-08-27 01:42 UTC, Jason-ZW requested changes
Others LGTM

2021-08-27 01:42 UTC, Jason-ZW commented on charts/rancher-f5cis/v0.0.2/templates/deployment.yaml
> +            - "--bigip-partition={{ .Values.partition }}"
左右的空格是否跟下面保持一致？

2021-08-27 02:00 UTC, jianghang8421 commented on charts/rancher-f5cis/v0.0.2/templates/deployment.yaml
> +            - "--bigip-partition={{ .Values.partition }}"
已修改

2021-08-31 02:56 UTC, Jason-ZW approved these changes

2021-08-31 02:56 UTC, merged